-- Создаем таблицу для хранения промптов

create table if not exists agent_prompt_instructions(
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	agent_name text unique,
	prompt text
);

 -- Создаем таблицу для postgres chat memory (контекст диалогов)

 create table if not exists chat_histories (
 	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 	session_id varchar not null,
 	message jsonb not null,
 	created_at timestamp with time zone DEFAULT now()
 );

 -- Создаем таблицу для хранения истории переписки в человеческом виде по всем кто общается с ботом

 create table if not exists message_logs (
 	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 	chat_id bigint not null,
 	username text,
 	role text,
 	message text,
 	name text,
 	created_at timestamp with time zone DEFAULT now()
 );